parameters:
  dockerServiceConnection: '' 
  acrName: ''                   # required (e.g., acrstronggnat)
  imageName: ''                 # required (e.g., python-microservice)
  dockerfilePath: ''            # required
  buildContext: '.'             # optional
  registryName: ''

stages:
- stage: BuildAndPush
  displayName: Build & Push Image
  jobs:
  - job: docker_build_push
    displayName: Docker build & push
    steps:
    - checkout: self
      fetchDepth: 0

    - template: step-resolve-tag.yaml

    - bash: |
        set -e
        echo "Logging in to Azure with VM managed identity…"
        az login --identity 1>/dev/null

        echo "ACR docker login…"
        # Approach 1: direct docker login via ACR (needs docker daemon)
        # This will perform a 'docker login' for you if Docker is available
        az acr login -n ${{ parameters.registeryName }}
    - task: Docker@2
      displayName: Build & Push (immutable + env tag)
      inputs:
        command: 'buildAndPush'
        repository: '${{ parameters.imageName }}'      # repo inside ACR
        dockerfile: '${{ parameters.dockerfilePath }}'
        buildContext: '${{ parameters.buildContext }}'
        # containerRegistry: '${{ parameters.dockerServiceConnection }}'
        tags: latest

    # - bash: |
    #     mkdir -p out
    #     cat > out/image-metadata.json <<EOF
    #     {
    #       "acrLoginServer": "${{ parameters.acrName }}.azurecr.io",
    #       "imageName": "${{ parameters.imageName }}",
    #       "buildTag": "$(Build.SourceBranchName)-$(Build.BuildId)",
    #       "envTag": "$(envTag)"
    #     }
    #     EOF
    #     cat out/image-metadata.json
    #   displayName: "Write & show image metadata"

    # - publish: out
    #   artifact: image-metadata
    #   displayName: "Publish image metadata artifact"
