resources:
  pipelines:
    - pipeline: ci              # alias
      source: ci                # <-- must be EXACT CI pipeline name in Azure DevOps
      trigger:
        branches:
          include:
            - main

trigger: none

pool:
  name: pwc-task

variables:
  ACR_NAME: 'acrtaskpwc'
  IMAGE_NAME: 'user-product-svc'
  K8S_SC: 'sc-aks-connection'
  NS: 'default'
  K8S_MANIFEST_PATH: 'k8s'
  K8S_CONTAINER_NAME: 'flask-app'

stages:
- stage: Deploy
  displayName: Deploy
  jobs:
  - template: .pipeline/templates/job-deploy-k8s.yaml
    parameters:
      deploymentJobName: 'dev'
      displayName: 'Deploy to default Environment'
      environmentName: 'default'
      kubernetesServiceConnection: $(K8S_SC)
      namespace: '$(NS)'
      manifestPath: $(K8S_MANIFEST_PATH)
      imageRepository: '$(ACR_NAME).azurecr.io/$(IMAGE_NAME)'
      imageTag: $(resources.pipeline.ci.runID)     
      containerName: $(K8S_CONTAINER_NAME)
