apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      # If your image is private, uncomment the next line and create the secret
      # imagePullSecrets:
      #   - name: regcred
      containers:
        - name: flask-app
          image: acrtaskpwc.azurecr.io/user-product-svc:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "256m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "128Mi"
