apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: microservices
  labels:
    app: flask-app

spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80          # external port
      targetPort: 5000  # container port
